import { StyleSheet } from "react-native";

const lstyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    paddingVertical: 30,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#000068",
    fontFamily: "PlayFair",
  },
  profileImageWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
  },

  subtitle: {
    fontSize: 14,
    color: "#6C7480",
    fontWeight: 300,
    fontFamily: "Lexend",
  },
  profileImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  searchContainer: {
    flexDirection: "row",
    borderRadius: 50,
    alignItems: "center",
    paddingHorizontal: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#CFD3D4",
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    fontSize: 14,
    fontFamily: "Lexend",
  },
  filterButton: {
    padding: 10,
  },
  leadCard: {
    backgroundColor: "#FAFAFC",
    borderRadius: 10,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#F7F7F7",
  },
  leadInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  leadLogo: {
    width: 24,
    height: 24,
    marginRight: 20,
  },
  leadIcon: {
    marginRight: 5,
  },
  leadNameContainer: {
    flexDirection: "row",
    marginBottom: 10,
    alignItems: "center",
    gap: 2,
    backgroundColor: "#FFFFFF",
    borderRadius: 50,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  leadName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000",
    fontFamily: "Lexend",
  },
  visits: {
    fontSize: 12,
    color: "#777",
    fontFamily: "Lexend",
  },
  activityCard: {
    backgroundColor: "#FAFAFC",
    borderRadius: 20,
    padding: 15,
    marginBottom: 20,
    shadowColor: "#000",
    // shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
  },
  activityDate: {
    fontSize: 14,
    color: "#555",
    marginBottom: 10,
    fontFamily: "Lexend",
  },
  activityRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  activityName: {
    fontSize: 16,
    marginBottom: 15,
    fontFamily: "Lexend",
    fontWeight: "bold",
    color: "#6C7480",
    maxWidth: "85%",
  },
  activityTime: {
    fontSize: 14,
    color: "#777",
    fontFamily: "Lexend",
  },
  activityDetail: {
    fontSize: 14,
    color: "#333",
    fontWeight: 500,
    fontFamily: "Lexend",
    marginBottom: 15,
  },
  typeContainer: {
    backgroundColor: "#E9F9EA",
    borderRadius: 24,
    paddingVertical: 8,
    paddingHorizontal: 20,
    color: "#1EBA2D",
    borderColor: "#1EBA2D",
    borderWidth: 0.5,

    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  reminderTime: {
    color: "#fff",
    fontSize: 12,
    fontFamily: "Lexend",
    fontWeight: 300,
  },
  reminderTask: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Lexend",
    fontWeight: "500",
    marginBottom: 10,
  },
  reminderFooter: {
    marginTop: "auto",
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  reminderFooterText: {
    color: "#333333",
    fontSize: 12,
    fontFamily: "Lexend",
    fontWeight: 300,
  },
  footerContainer: {
    backgroundColor: "#F9F9F9",
    borderRadius: 24,
    padding: 8,
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
});

export default lstyles;
